In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
print(np.__version__)

2.1.3


In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
print(f"arr[0] :{arr[0]}")
print(f"arr[3] :{arr[3]}")
print(f"arr[-1] :{arr[-1]}")

arr[0] :1
arr[3] :4
arr[-1] :5


In [8]:
print(f"arr[1] + arr[3] :{arr[1] + arr[3]}")
print(f"arr[4] - arr[0] :{arr[4] - arr[0]}")

arr[1] + arr[3] :6
arr[4] - arr[0] :4


In [11]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(f"arr1 :\n{arr1}")

print(f"arr1[1, 3] :{arr1[1, 3]}")

arr1 :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr1[1, 3] :9


In [12]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"arr2 :\n{arr2}")

arr2 :
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
print(arr2[0, 1, 2])

6


In [16]:
print(f"arr2[1, -1, -2] :{arr2[1, -1, -2]}")

arr2[1, -1, -2] :11


## Slicing

In [21]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr1[1:5])

print(arr1[4:])

print(arr1[:-3])

print(arr1[1:5:2])

print(arr1[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[2 4]
[1 3 5 7]


In [25]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(f'arr2 :\n{arr2}')

print(arr2[1, 1:4])

print(arr2[0:2, 2])

print(arr2[0:2, 1:4])

arr2 :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# Numpy Data Types

In [27]:
arr1 = np.array([1, 2, 3, 4, 5])

print(f"arr1 :{arr1}")

print(f"Data Type :{arr1.dtype}")

arr1 :[1 2 3 4 5]
Data Type :int64


In [28]:
arr1 = np.array(['apple', 'orange', 'grapes', 'gauva'])

print(f"arr1 :\n{arr1}")

print(arr1.dtype)

arr1 :
['apple' 'orange' 'grapes' 'gauva']
<U6
