# Data types

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4 ,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [5]:
fruits = np.array(['apple', 'orange', 'grapes'])
print(fruits)
print(type(fruits))
print(fruits.dtype)

['apple' 'orange' 'grapes']
<class 'numpy.ndarray'>
<U6


In [6]:
arr = np.array([1, 2, 3, 4, 5], dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


### | byte order flag, S - string data type and 1 is the size

In [7]:
arr = np.array([1, 2, 3, 4, 5], dtype = "i4")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [10]:
arr = np.array(['a', '2', '3', 'b', '5'], dtype='i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [15]:
arr = np.array([1.5, 3.4, 6.8])
print(arr)

arr1 = arr.astype("i")
print("-" * 60)
print(arr1)
print(arr1.dtype)

print("-" * 60)
arr2 = arr.astype(int)
print(arr2)
print(arr2.dtype)

[1.5 3.4 6.8]
------------------------------------------------------------
[1 3 6]
int32
------------------------------------------------------------
[1 3 6]
int64


In [16]:
arr = np.array([1, 0, -1, 0.5, 0])
print(arr)

print("-" * 60)
arr1 = arr.astype(bool)
print(arr1)

[ 1.   0.  -1.   0.5  0. ]
------------------------------------------------------------
[ True False  True  True False]


copy VS View

In [19]:
arr = np.array([1, 2, 3, 4, 5])
print(f"arr :{arr}")

arr1 = arr.copy()
print(f"arr1 :{arr1}")

print("-" * 60)
arr1[3] = 400

print("-" * 60)
print(f"arr1 :{arr1}")
print(f"arr  :{arr}")


arr :[1 2 3 4 5]
arr1 :[1 2 3 4 5]
------------------------------------------------------------
------------------------------------------------------------
arr1 :[  1   2   3 400   5]
arr  :[1 2 3 4 5]


In [20]:
arr = np.array([10, 20, 30, 40, 50])
print(f"arr :{arr}")

print("-" * 60)
arr1 = arr.view()

arr1[2] = 333
print("-" * 60)
print(f"arr :{arr}")
print(f"arr1 :{arr1}")

arr :[10 20 30 40 50]
------------------------------------------------------------
------------------------------------------------------------
arr :[ 10  20 333  40  50]
arr1 :[ 10  20 333  40  50]


# Array Shape

In [23]:
arr = np.array([[1, 2, 3, 4] , [5, 6, 7, 8]])
print(f"arr :\n{arr}")

print(f"arr.shape - {arr.shape}")

arr :
[[1 2 3 4]
 [5 6 7 8]]
arr.shape - (2, 4)


In [24]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr)
print(f"shape of the array :{arr.shape}")

[[[[[1 2 3 4 5]]]]]
shape of the array :(1, 1, 1, 1, 5)


## Reshaping Arrays

In [32]:
arr =np.array([1, 2, 3, 4, 5, 6 ,7, 8, 9, 10, 11, 12])
print(arr)
print(arr.shape)

print("-" * 60)
arr1 = arr.reshape(2, 6)
print(arr1)
print(arr1.shape)

print("-" * 60)
arr2 = arr.reshape(4, 3)
print(arr2)
print(arr2.shape)

print("-" * 60)
arr3 = arr.reshape(2, 3, 2)
print(arr3)
print(arr3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
------------------------------------------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
------------------------------------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
------------------------------------------------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

arr1 = arr.reshape(3, 3)
print(arr1)

[1 2 3 4 5 6 7 8]


ValueError: cannot reshape array of size 8 into shape (3,3)

In [36]:
# returns the copy of view - so no modification
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(f"arr :{arr}")

arr1 = arr.reshape(2, 4).base

print(arr1)

print(f"arr :{arr}")

arr :[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
arr :[1 2 3 4 5 6 7 8]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

arr1 = arr.reshape(2, 2, -1)
print(arr1)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"arr :{arr}")

arr1 = arr.flatten()

print(arr1)

arr :[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [39]:
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8]])
print(f"arr :{arr}")

arr1 = arr.reshape(-1)

print(arr1)

arr :[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
