## iterating Arrays

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(f"arr :{arr}")

for x in arr:
    print(x, end=" ")

arr :[1 2 3 4 5]
1 2 3 4 5 

In [6]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"arr :{arr}")

for x in arr:
    print(x)

print("-" * 60)
# list comprehension
print([x for x in arr])

# print all the elements using list comprehension
print([i for x in arr for i in x])

arr :[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[5 6 7 8]
------------------------------------------------------------
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(f"arr :\n{arr}")

for i in arr:
    print(i)

print("-" * 60)
for x in np.nditer(arr):
    print(x)

print("-" * 60)

arr1 = np.array([[[1, 2], [3, 4], [5, 6], [7,8 ]]])
print(f"arr1 :\n{arr1}")

for x in np.nditer(arr):
    print(x)    

arr :
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------------------------------------
1
2
3
4
5
6
7
8
9
------------------------------------------------------------
arr1 :
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
1
2
3
4
5
6
7
8
9


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(f"arr :{arr}")

for x in np.nditer(arr, flags = ['buffered'], op_dtypes=['S']):
    print(x)

arr :[1 2 3 4 5]
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')


Iterating with different step size

In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"arr :\n{arr}")

print("-" * 60)
for x in np.nditer(arr[:, ::2]):
    print(x)

arr :
[[1 2 3 4]
 [5 6 7 8]]
------------------------------------------------------------
1
3
5
7


Enumerated iterations

In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(f"arr :\n{arr}")

for idx, x in np.ndenumerate(arr):
    print(idx, x)

arr :
[1 2 3 4 5]
(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [18]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"arr :\n{arr}")

print("-" * 60)
for idx, x in np.ndenumerate(arr):
    print(idx, x)

arr :
[[1 2 3 4]
 [5 6 7 8]]
------------------------------------------------------------
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# joining arrays

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6]


In [24]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(f"arr1 :\n{arr1}")
print("-" * 60)
print(f"arr2 :\n{arr2}")

print("-" * 60)
arr3 = np.concatenate((arr1, arr2), axis = 0)
print(arr3)

print("-" * 60)
arr4 = np.concatenate((arr1, arr2), axis = 1)
print(arr4)

arr1 :
[[1 2]
 [3 4]]
------------------------------------------------------------
arr2 :
[[5 6]
 [7 8]]
------------------------------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------------------------------------------------------------
[[1 2 5 6]
 [3 4 7 8]]


# stack

In [28]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

print("-" * 60)
# hstack
arr3 = np.hstack((arr1, arr2))
print(f"arr3 :{arr3}")

print("-" * 60)
# vstack
arr4 = np.vstack((arr1, arr2))
print(f"arr4 :\n{arr4}")

print("-" * 60)
# dstack
arr5 = np.dstack((arr1,  arr2))
print(f"arr5 :\n{arr5}")

arr1 :[1 2 3 4]
arr2 :[5 6 7 8]
------------------------------------------------------------
arr3 :[1 2 3 4 5 6 7 8]
------------------------------------------------------------
arr4 :
[[1 2 3 4]
 [5 6 7 8]]
------------------------------------------------------------
arr5 :
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# split

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(f"arr :{arr}")

print("-" * 60)
arr1 = np.array_split(arr)
print(arr1)

arr :[1 2 3 4 5 6]
------------------------------------------------------------
[array([1, 2]), array([3, 4]), array([5, 6])]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(f"arr :{arr}")

arr1 = np.array_split(arr, 4)
print(arr1)

arr :[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)

print("-" * 60)
arr1 = np.array_split(arr, 3, axis=0)
print(arr1)

print("-" * 60)
arr2 = np.array_split(arr, 3, axis=1)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
------------------------------------------------------------
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
------------------------------------------------------------
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


search

In [34]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [49]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [47]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr,7, side="right")

print(x)

2


Sort

In [53]:
arr = np.array([7, 4, 10, 1, 5, 8, 3, 6, 2, 9])
print(f"arr :{arr}")

print("Ascending Order :", np.sort(arr))
print("Descending Order :", np.sort(arr)[::-1])


arr :[ 7  4 10  1  5  8  3  6  2  9]
Ascending Order : [ 1  2  3  4  5  6  7  8  9 10]
Descending Order : [10  9  8  7  6  5  4  3  2  1]


In [58]:
arr = np.array([[5, 2, 3, 1, 4], [9, 6, 10, 7, 8]])
print(arr)

print("-" * 60)
print(np.sort(arr))

print("-" * 60)
print(np.sort(arr, axis=0))

print("-" * 60)
print(np.sort(arr, axis=1))

[[ 5  2  3  1  4]
 [ 9  6 10  7  8]]
------------------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
------------------------------------------------------------
[[ 5  2  3  1  4]
 [ 9  6 10  7  8]]
------------------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
names = np.array(['kevin', 'salter', 'jack', 'mike', 'bob', 'ana'])
print(f"names :{names}")

print(np.sort(names))
print(np.sort(names)[::-1])

names :['kevin' 'salter' 'jack' 'mike' 'bob' 'ana']
['ana' 'bob' 'jack' 'kevin' 'mike' 'salter']
['salter' 'mike' 'kevin' 'jack' 'bob' 'ana']


Filter

In [68]:
arr = np.array(list(range(1, 11)))
print(arr)

x = [True,False, False, True, True, False, False, True, True, False]
arr1 = arr[x]

print(arr1)

print("-" * 60)

filtered = []

for i in arr:
    if i % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)

res = arr[filtered]
print(res)


[ 1  2  3  4  5  6  7  8  9 10]
[1 4 5 8 9]
------------------------------------------------------------
[ 2  4  6  8 10]


# Broadcasting

In [71]:
arr = np.array([1, 2, 3, 4])
print(arr)

print("-" * 60)
res = arr + 1
print(res)

[1 2 3 4]
------------------------------------------------------------
[2 3 4 5]


In [72]:
arr1 = np.array([2, 4, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

res = arr1 + arr2
print(res)

[[ 3  6  9]
 [ 6  9 12]]


In [73]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([6])

print(arr)
print(arr1)

res = arr + arr1
print(res)

[1 2 3 4 5]
[6]
[ 7  8  9 10 11]


In [77]:
arr1 = np.array([[1], [2], [3]])
print(arr1)
print(arr1.shape)

arr2 = np.array([10 ,20, 30])
print(arr2)
print(arr2.shape)

res = arr1 + arr2
print(res)

[[1]
 [2]
 [3]]
(3, 1)
[10 20 30]
(3,)
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [82]:
temperatures = np.array([
    [30, 32, 34, 33, 32],
    [25, 27, 29, 28, 26],
    [20, 22, 24, 23, 21]
])

print(temperatures)

print("-" * 60)

corrections = np.array([1.5, -0.5, 2.0])

res_temp = temperatures + corrections[:, np.newaxis]

print(res_temp)

[[30 32 34 33 32]
 [25 27 29 28 26]
 [20 22 24 23 21]]
------------------------------------------------------------
[[31.5 33.5 35.5 34.5 33.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


In [86]:
data = np.array([10, 20, 30, 40, 50])
print(data)

print("MEAN :", np.mean(data))
print("MEDIAN :", np.median(np.array([10, 20, 30, 40])))


[10 20 30 40 50]
MEAN : 30.0
MEDIAN : 25.0


In [87]:
data = np.genfromtxt("data.txt", delimiter=",", filling_values=0)
print(data)

[[1. 2. 3.]
 [4. 0. 6.]
 [0. 7. 8.]
 [0. 0. 9.]]


In [88]:
# Load the data from the text file
sales = np.genfromtxt("Stocks.txt", delimiter=",", names=True, dtype=None, encoding='utf-8')

# Extract numeric columns
quantities = sales['Quantity'].astype(float)
unit_price = sales['UnitPrice'].astype(float)

print(quantities)
print(unit_price)

[6. 6. 8.]
[2.55 3.39 2.75]


In [90]:
# load the csv file
data = np.genfromtxt("sample.csv", delimiter=",", dtype=None, encoding='utf-8')

# convert first column f0 to datetime64[D]
dates = data['f0'].astype('datetime64[D]')
print(dates)

data = data['f1']
print(data)

['2023-01-01' '2023-01-02' '2023-01-03']
[100 200 150]
